name: flutter_remote_control
description: A new Flutter application.

version: 1.0.0
homepage: https://github.com/simplezhli/flutter_remote_control


environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_swiper_null_safety: ^1.0.2
  # 振动 https://github.com/benjamindean/flutter_vibration
  vibration: ^1.7.6
  vibration_web: 1.6.5
  # 绘制虚线 https://github.com/dnfield/flutter_path_drawing
  path_drawing: ^1.0.1
  # 用来替代dart:html，便于导包 https://github.com/dint-dev/universal_html
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
